language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: bNoWf1omd+06bv/wQF4xXIshdu16O3MFEoqJS01avCaRMP1s4CF9UeJOFYG5imU3qvltOCSfYM5p00Wx19JAi++57gqGTAe6P4gKWxYjwLIDn8/98pUI+mmX7HcqLuPl7OxjDvWiiDQA0gDXqVwXLMUQ/vc1ntDUAUXG0rSOsJaI5R8G62sS3B5Sgu3XUXE7ih4OckMYUISjmmgTBjCR3rLY3qpbKESjbFRERog4AXBV09dJ3udbuZVgJ0KbDBey90QFyVMXNAX+ZB0d5WwoUM5e1n7QPQLWKYZ1OcrAb34fOpqwCKaV8cVZzXXDcbVZsucyN1NOZwule95qapf5NrD469IBRv+P4KujBiBLSmOgKHg525M8Ku86j/ixy7oMiwj/XFLBjEqUDw9SY62ratnSzK/BtkEm2TGHptK1vwVyFYrX6PGpmbMxmrsBzIeLMoszchHBAJ/aLrLm0vCUisiJzDOaAxr0+uctEjIGRG/1aLqP9nDKp6FK32fHtVaK509IQFb4VLrN81TSWF6n92v362zlXZ4Gcbusk+DH1m4fhitbA6wksWf5Ra1mJg7AvYNenCYa/oyvdGD1Gj7IzX3cHpf9IEb5V8EQu1lpNOc1UF5YJsDFNWBoZgS1lyM9T8yHFk7rX1Drmhr6wQvq9Dlv8gGqczYq45lo5tAVa9s=
  on:
    tags: true
    repo: davewd/python_cheatsheet
    python: 3.6
after_success:
- pip install codecov
- codecov
